const transactions = [
  {
    id: 1,
    date: "2025-03-01",
    amount: 5000,
    category: "Salary",
    type: "income",
    description: "Monthly Salary",
  },
  {
    id: 2,
    date: "2025-03-02",
    amount: 150,
    category: "Food",
    type: "expense",
    description: "Lunch",
  },
  {
    id: 3,
    date: "2025-03-05",
    amount: 60,
    category: "Transport",
    type: "expense",
    description: "Bus Fare",
  },
  {
    id: 4,
    date: "2025-03-08",
    amount: 120,
    category: "Entertainment",
    type: "expense",
    description: "Movie Tickets",
  },
  {
    id: 5,
    date: "2025-03-10",
    amount: 800,
    category: "Housing",
    type: "expense",
    description: "Rent",
  },
  {
    id: 6,
    date: "2025-03-12",
    amount: 200,
    category: "Shopping",
    type: "expense",
    description: "Groceries",
  },
  {
    id: 7,
    date: "2025-03-15",
    amount: 300,
    category: "Freelance",
    type: "income",
    description: "Project Payment",
  },
  {
    id: 8,
    date: "2025-03-18",
    amount: 50,
    category: "Food",
    type: "expense",
    description: "Dinner",
  },
  {
    id: 9,
    date: "2025-03-20",
    amount: 120,
    category: "Utilities",
    type: "expense",
    description: "Electricity Bill",
  },
  {
    id: 10,
    date: "2025-03-25",
    amount: 400,
    category: "Investment",
    type: "income",
    description: "Investment Return",
  },
  {
    id: 11,
    date: "2025-03-28",
    amount: 75,
    category: "Health",
    type: "expense",
    description: "Medicines",
  },
];

export default transactions;
