const transactions = [
  {
    id: 1,
    date: "2025-03-01",
    amount: 50000,
    category: "Salary",
    type: "income",
    description: "Monthly Salary",
  },
  {
    id: 2,
    date: "2025-03-02",
    amount: 15000,
    category: "Housing",
    type: "expense",
    description: "Monthly Rent",
  },
  {
    id: 3,
    date: "2025-03-05",
    amount: 6000,
    category: "Food",
    type: "expense",
    description: "Supermarket Groceries",
  },
  {
    id: 4,
    date: "2025-03-08",
    amount: 800,
    category: "Food",
    type: "expense",
    description: "Zomato Order",
  },
  {
    id: 5,
    date: "2025-03-10",
    amount: 2500,
    category: "Transport",
    type: "expense",
    description: "Petrol for Bike",
  },
  {
    id: 6,
    date: "2025-03-15",
    amount: 1500,
    category: "Utilities",
    type: "expense",
    description: "Electricity Bill",
  },
  {
    id: 7,
    date: "2025-03-18",
    amount: 8000,
    category: "Freelance",
    type: "income",
    description: "Side Project Payment",
  },
  {
    id: 8,
    date: "2025-03-20",
    amount: 3000,
    category: "Shopping",
    type: "expense",
    description: "Myntra Clothing",
  },
  {
    id: 9,
    date: "2025-03-22",
    amount: 600,
    category: "Entertainment",
    type: "expense",
    description: "Netflix Subscription",
  },
  {
    id: 10,
    date: "2025-03-25",
    amount: 1200,
    category: "Health",
    type: "expense",
    description: "Pharmacy Medicines",
  },
];

export default transactions;
